

#' add.trophiclvl
#'
#' Add.trophiclvl is a function that assigns ecological trophic levels (such as predator, grazer, or phototroph) to a dataset of organisms (taxo) generated by the function aa.taxo. It cross-references your taxonomic data against a master reference database (trophic_affiliation_of_organisms from the package or an external one) and provides an interactive user interface to handle any missing entries.
#' object_annotation_hierarchy2 = object annotation hierarchy from ecotaxa with corrected delim >.
#' Type = OTU main type "Living, non-living, etc."
#' Sub_Type = OTU sub type "Diatoms, Copepods, etc."
#' Value = Trophic level "Unknown = 3.5, Predators = 3, Omnivorous = 2.5, Grazer = 2, Mixotrophe = 1.5, Phototroph = 1 and None = -1"
#'
#' @param taxo OTU table generated with "add_taxo" containing trophic levels and main OTU groups.
#' @param output file output to save the new zoo table if edited.
#'
#' @return A taxonomic table with also trophic levels.
#' @export
#'
#' @examples add.trophiclvl(taxo=table from add.taxo, output=where to save the table)
add.trophiclvl <- function(taxo, output) {
  # Helper function to eliminate the redundant cleanup code
  finalize_trophic_data <- function(df) {
    df %>%
      mutate(
        # Handle non-living and temporary flags based on taxonomic column n1
        Type = case_when(
          n1 == "temporary"  ~ "temporary",
          n1 == "not-living" ~ "non_living",
          is.na(Type)        ~ "temporary",
          TRUE               ~ Type
        ),
        Sub_type = case_when(
          n1 == "temporary"  ~ "temporary",
          is.na(Sub_type)    ~ "temporary",
          TRUE               ~ Sub_type
        ),
        # Assign values based on the finalized Type
        Value = case_when(
          Type == "non_living" ~ -1,
          Type == "temporary"  ~ 3.5,
          TRUE                 ~ Value
        )
      )
  }
  
  # 1. Initial merge with master database
  zo <- trophic_affiliation_of_organisms
  zoo <- merge(taxo, zo, all.x = TRUE) %>% finalize_trophic_data()
  
  # 2. Identify missing objects
  missing_taxa <- zoo$object_annotation_hierarchy2[is.na(zoo$Type) | zoo$Type == "temporary"]
  
  # Only prompt if there are actual missing or unclassified taxa
  if (any(is.na(zoo$Type)) && length(missing_taxa) > 0) {
    
    # Define validation menus for the interactive GUI
    liste.choix <- zo %>% 
      mutate(Category = paste0(Type, ">", Sub_type)) %>% 
      select(Category) %>% 
      distinct()
    
    liste.value <- data.frame(
      Value = c(-1, 1, 1.5, 2, 2.5, 3, 3.5),
      Trophic = c("None", "Phototroph", "Mixotroph", "Grazer", "Omnivorous", "Predator", "Unknown")
    )
    
    # Create Missing Taxa
    msg_text <- paste0("These taxa do not exist in the database. Would you like to create them?\n\n", 
                       paste(head(missing_taxa, 10), collapse = "\n"))
    
    user_choice <- dlg_message(msg_text, type = "yesno")$res
    
    if (user_choice == "yes") {
      # Open editor
      replace_df <- data.frame(object_annotation_hierarchy2 = missing_taxa, Category = "temporary>temporary", Trophic = "Unknown")
      replace_df <- data_edit(replace_df,
                              col_options = list(Category = liste.choix$Category, Trophic = liste.value$Trophic), 
                              viewer = "pane")
      
      # Process input and append to database
      replace_df <- replace_df %>%
        separate(Category, into = c("Type", "Sub_type"), sep = ">") %>%
        merge(liste.value, by = "Trophic") %>%
        select(-Trophic)
      
      zo <- bind_rows(zo, replace_df) %>% as.data.frame()
      write_csv(zo, file.path(output, "summary", "trophic_affiliation_of_organisms.csv"))
      
      # Re-merge updated database
      zoo <- merge(taxo, zo, all.x = TRUE) %>% finalize_trophic_data()
      
    } else {
      # Import an existing database instead or not
      import_choice <- dlg_message("Do you want to import an existing database? If no, they will be classified as temporary.", type = "yesno")$res
      
      if (import_choice == "yes") {
        zo <- read.csv(file.choose(), sep = ",")
        zoo <- merge(taxo, zo, all.x = TRUE) %>% finalize_trophic_data()
      } else {
        return(zoo)
      }
    }
  }
  return(zoo)
}
