#' compute_bv
#'
#' Compute all types of biovolumes (elli, plain, riddled) for each objects of one sample and save the new tsv files in the output directory.
#' Also compute conversion factor (by acquisition and by sample).
#' Convert the metadata to homogeneous units and replace NA by 1.
#'
#' @param path path to the directory containing all the tsv files
#' @param output path to the output directory where the results are saved
#' @param metadata metadata table generated by "check_metadata" or similar 
#'
#' @return Compute biovolumes for all the samples and save the new tsv files.
#' @export
#'
#' @examples compute_bv(path=path of the file, output=path where to save results, metadata=NULL)
#'
# Function to compute biovolumes for one file
compute_bv <- function(path, output, metadata = NULL, instru) {
  options(dplyr.summarise.inform = FALSE)

 # Replace NA by 1 
  for (i in unique(metadata$unique_id)) {
    if (sum(is.na(metadata[metadata$unique_id == i, ])) > 0) {
      pb <- colnames(metadata[metadata$unique_id == i, ])[is.na(metadata[metadata$unique_id == i, ])]
      print(paste0("Warning! [sample: ", unique(metadata$sample_id), "] These metadata do not have value. Default is 1: ", paste(pb, collapse = ", ")))
      for (col_name_to_set_one in pb) {
        if (col_name_to_set_one %in% colnames(metadata)) {
          metadata[[col_name_to_set_one]][is.na(metadata[[col_name_to_set_one]]) & metadata$unique_id == i] <- 1
        }
      }
      metadata[is.na(metadata) & metadata$unique_id == i] <- 1
    }
  }

  # Dispatch to instrument-specific processing function
  if (instru == "PlanktoScope") {
    data <- process_planktoscope_data(data, metadata)
  } else if (instru == "FlowCam") {
    data <- process_flowcam_data(data, metadata)
  } else if (instru == "ZooScan") {
    data <- process_zooscan_data(data, metadata)
  } else if (instru == "IFCB") {
    data <- process_ifcb_data(data, metadata)
  } else {
    stop(paste0("Unknown instrument: ", instru))
  }

  id <- unique(data$sample_id) 

  # --- Common Biovolume Computations (apply to all instruments after specific processing) ---
  data <- mutate(data,
                 major = object_major * pixelsize,
                 minor = object_minor * pixelsize,
                 area_exc = object_area_exc * (pixelsize^2),
                 area = object_area * (pixelsize^2),
                 area_origin = object_area,
                 ar_elli = pi * (major / 2) * (minor / 2),
                 BV_elli = (4 / 3) * (minor / 2) * ar_elli,
                 ESD_plain = 2 * (sqrt(area / pi)),
                 ESD_riddled = 2 * (sqrt(area_exc / pi)),
                 R3_riddled = (ESD_riddled / 2)^3,
                 R3_plain = (ESD_plain / 2)^3,
                 BV_riddled = (4 / 3) * pi * R3_riddled,
                 BV_plain = (4 / 3) * pi * R3_plain,
                 AB = 1,
                 percentValidated = sum(object_annotation_status == "validated", na.rm = TRUE) / n() * 100 
  )


  # Biovolume class parameters (common)
  smin = 1e-12 # minimum size
  smax = 1e4 # maximum size
  k = 2^(1/4) # bin

  nb <- ceiling(log(smax / smin, base = k))
  x <- smin * k^(1:nb)
  x1 <- c(0, diff(x))

  class.f <- function(y) {
    a <- x[x <= y][which.min(abs(x[x <= y] - y))]
    b <- x[x > y][which.min(abs(x[x > y] - y))]
    id <- match(b, x)
    norm <- x1[id]
    tot <- data.frame(
      size_class.min = a,
      size_class.max = b,
      size_class.id = id,
      size_class.norm = norm
    )
    return(tot)
  }

  classes <- sapply(data$BV_plain, class.f) %>% t %>% as.data.frame %>% sapply(as.numeric)
  colnames(classes) <- paste0(colnames(classes), "_plain")
  data <- cbind(data, classes)

  classes <- sapply(data$BV_riddled, class.f) %>% t %>% as.data.frame %>% sapply(as.numeric)
  colnames(classes) <- paste0(colnames(classes), "_riddled")
  data <- cbind(data, classes)

  classes <- sapply(data$BV_elli, class.f) %>% t %>% as.data.frame %>% sapply(as.numeric)
  colnames(classes) <- paste0(colnames(classes), "_elli")
  data <- cbind(data, classes)

  # Save file with the new columns
  write_csv2(data, paste0(file.path(output, id), ".csv"))

  print(paste0("done : ", unique(data$sample_id)))

  options(dplyr.summarise.inform = TRUE)

  return(data)
}

