#' graph.project
#'
#' Print ggplot graphics to summarise the project (comparison of all samples).
#' Return :
#' 1. Text summary of all the project
#' 2. living/not-living/temporary BV and AB graph
#' 3. Not-Living and Living (based on the OTU database) BV and AB graph
#' 4. NBSS (color and curve)
#' 5. Relative NBSS
#' 6. Shannon index
#'
#' @param x bss data.table produced by "BSS_table"
#' @param final_metadata metadata table generated by "check_metadata" used to do the analysis
#' @param taxo taxonomic table generated with "add_trophiclvl" and "add_taxo"
#' @param bv.type elli, plain or riddled biovolume. default is "elli"
#' @param living.only TRUE by default, for NBSS plots
#'
#' @return A set of graphics to summarise the project.
#' @export
#'
#' @examples graph.project(x=bss table of all the project, final_metadata, taxo=trophic_affiliation_of_organisms.csv, bv.type="elli", living.only=TRUE)
graph.project <- function(x, final_metadata, taxo, bv.type="elli", living.only=T) {
suppressMessages(sf::sf_use_s2(FALSE))
  
  # Select type of biovolume and add taxonomic units
  x <- filter(x, type==bv.type) %>% merge(taxo, "object_annotation_hierarchy", all.x=T)
  
  # Transform date & time and remove unnecessary metadata
  t <- final_metadata %>% select(sample_id, sample_num, object_time, object_date, object_lat, object_lon) %>%
    mutate(time=as.POSIXct(paste(object_date, object_time))) %>% select(sample_id, sample_num, time, object_lat, object_lon)
  
  x <- merge(x, t, all.x=T)
  x$ESD <- bv_to_esdum(x$max)

  # Select the living particles only 
  living.x <- x %>%
    filter(Type=="living" & Sub_type != "detritus")
  
  #Compute Shannon Index between categories of each sample
  shannon_data <- living.x %>%
  group_by(object_annotation_category, sample_num) %>%
  summarise(AB = sum(AB, na.rm = TRUE), .groups = "drop") %>%
  group_by(sample_num) %>%
  summarise(Shannon = vegan::diversity(AB), .groups = "drop")

  #Merge to the living dataset
  living.x <- left_join(living.x, shannon_data, by = "sample_num")
  
  # Set commun parameters for the maps
   ex = 7
  latmin <- min(x$object_lat, na.rm=T)-ex
  lonmin <- min(x$object_lon, na.rm=T)-ex
  latmax <- max(x$object_lat, na.rm=T)+ex
  lonmax <- max(x$object_lon, na.rm=T)+ex

  if(latmin<(-90)) latmin <- (-90)
  if(lonmin<(-180)) lonmin <- -180
  if(latmax>90) latmax <- 90
  if(lonmax>180) lonmax <- 180

  sf_use_s2(FALSE)

 bbox_area <- st_bbox(c(xmin = lonmin, ymin = latmin, xmax = lonmax, ymax = latmax), crs = 4326)
 
  worldmap <- ne_countries(scale = 'medium', type = 'map_units', returnclass = 'sf') %>%
              st_filter(st_as_sfc(bbox_area))
  
## Create a summary table for each station, use the living dataset as we compute AB / BV
  sample.point <- living.x %>% 
    group_by(sample_id,sample_num,time,object_lat,object_lon,Shannon) %>% 
    summarise(AB = sum(AB, na.rm = TRUE),BV = sum(BV, na.rm = TRUE), .groups = "drop") %>% 
    st_as_sf(coords=c("object_lon","object_lat"), crs=st_crs(worldmap))
  sample.point <- sample.point %>% 
    bind_cols(st_coordinates(sample.point))

   # Set common color palette
  plankton_groups_colors <- c("#709699", #cyanobacteria
               "#CD853F", #detritus
               "#8EE5EE", #artefact
               "#FAFABA", #other
               "#C9C4FF", #ciliophora
               "#B5D493", #dinoflagellata
               "#FAD4EB", #rhizaria
               "#1A9C75", #bacillariophyta
               "#E3E699", #dictyochophyceae
               "#EDB022", #crustacea
               "#E88F6B", #copepoda
               "#B0D6E0", #chaetognatha
               "#3B638A", #tunicata
               "#6999C7", #cnidaria
               "#C68181", #mollusca
               "#668F3B", #coccolithophyceae
               "#FFD3CF", #other_unidentified
               "#0073BD" #plastics
               )

  names(plankton_groups_colors)<- c("cyanobacteria","detritus","artefact","other","ciliophora","dinoflagellata",
                     "rhizaria","bacillariophyta","dictyochophyceae","crustacea",
                     "copepoda","chaetognatha","tunicata","cnidaria","mollusca",
                     "coccolithophyceae","other_unidentified","plastics")
  plankton_groups_colScale <- scale_colour_manual(name = "Taxonomic group",values = plankton_groups_colors)
  plankton_groups_colFill <- scale_fill_manual(name = "Taxonomic group",values = plankton_groups_colors)

  # SUMMARY OF THE PROJECT
  # ----------------------------------------------------------------------------
  #To delete as compute diversity on detritus as no ecological meaning
  div.all <- x %>% group_by(object_annotation_category) %>%
    summarise(AB=sum(AB, na.rm=T)) %>% select(AB) %>% vegan::diversity()
  div <- living.x %>% group_by(object_annotation_category) %>%
    summarise(AB=sum(AB, na.rm=T)) %>% select(AB) %>% vegan::diversity()

  text = paste0(
    "\nALL:\n",
    "\nNumber of samples:\n",
    length(unique(x$sample_id)),
    "\nMean abundance (ind.m-3):\n",
    round(mean(x$AB, na.rm=T),2)," ~",round(sd(x$AB, na.rm=T),2),
    "\nMean biovolume (mm3.mm-3):\n",
    round(mean(x$BV, na.rm=T),2)," ~",round(sd(x$BV, na.rm=T),2),
    "\nShannon Index:\n",
    round(div.all,2),

    "\n\n\nLIVING ONLY:\n",
    "\nNumber of samples:\n",
    length(unique(living.x$sample_id)),
    "\nMean abundance (ind.m-3):\n",
    round(mean(living.x$AB, na.rm=T),2)," ~",round(sd(living.x$AB, na.rm=T),2),
    "\nMean biovolume (mm3.mm-3):\n",
    round(mean(living.x$BV, na.rm=T),2)," ~",round(sd(living.x$BV, na.rm=T),2),
    "\nShannon Index:\n",
    round(div,2))

  print(ggplot() +
          annotate("text", x = 1, y=10, size=3, label = text) +
          theme_void())

  # BIOVOLUME AND ABUNDANCE TOTAL OF THE PROJECT
  # ----------------------------------------------------------------------------
  # living/not-living/temporary
  
  print(x %>% group_by(Type,sample_num) %>% 
          summarise(BV = sum(BV),.groups = "drop") %>% 
          ggplot(aes(x=factor(sample_num), y=BV, fill=Type)) +
          geom_col(stat="identity") +
          scale_fill_viridis_d(option = "D") +
          scale_y_continuous("Biovolume (mm3.m-3)", expand = expansion(mult = c(0, 0.05))) +
          xlab(NULL) +
          ggtitle("Total biovolume per sample") +
          labs(fill = "Type") +
          theme_bw() +
          theme(axis.text = element_text(size = 10),plot.title = element_text(hjust = 0.5, face = "bold")))

  print(x %>% group_by(Type,sample_num) %>% 
          summarise(AB = sum(AB),.groups = "drop") %>% 
          ggplot(aes(x=factor(sample_num), y=AB, fill=Type)) +
          geom_bar(stat="identity") +
          scale_fill_viridis_d(option = "D") +
          scale_y_continuous("Abundance (ind.m-3)", expand = expansion(mult = c(0, 0.05))) +
          xlab(NULL) +
          ggtitle("Total abundance per sample") +
          labs(fill = "Type") +
          theme_bw() +
          theme(axis.text = element_text(size = 10),plot.title = element_text(hjust = 0.5, face = "bold")))

  ## living only
  
  # Total biovolume 
  print(living.x %>% 
          group_by(Sub_type,sample_num) %>% summarise(BV=sum(BV),.groups = "drop") %>% 
          ggplot(aes(x=factor(sample_num), y=BV, fill=Sub_type)) +
          geom_bar(stat="identity") +
          plankton_groups_colFill +
          scale_y_continuous("Biovolume (mm3.m-3)", expand = expansion(mult = c(0, 0.05))) +
          xlab(NULL) +
          ggtitle("Biovolume of the living per sample") +
          theme_bw() +
          theme(axis.text = element_text(size = 10),plot.title = element_text(hjust = 0.5, face = "bold")))

  # Total abundance 
  print(living.x %>% 
          group_by(Sub_type,sample_num) %>% summarise(AB=sum(AB),.groups = "drop") %>% 
          ggplot(aes(x=factor(sample_num), y=AB, fill=Sub_type)) +
          geom_bar(stat="identity") +
          plankton_groups_colFill +
          scale_y_continuous("Abundance (ind.m-3)", expand = expansion(mult = c(0, 0.05))) +
          xlab(NULL) +
          ggtitle("Abundance of the living per sample") +
          theme_bw() +
          theme(axis.text = element_text(size = 10),plot.title = element_text(hjust = 0.5, face = "bold")))


# ----------------------------------------------------------------------
# Constrained Rounding Function to have the relative biovolume and relative abundance
# This function takes a vector of percentages (e.g., 33.3, 33.3, 33.4)
# and returns whole numbers that sum exactly to 100 (e.g., 33, 33, 34).
# ----------------------------------------------------------------------
constrain_round <- function(values) {
  # Calculate initial integer parts by rounding down
  rounded_values <- floor(values)
  
  # Calculate how much is 'missing' or 'extra' from 100 after flooring
  remainder <- 100 - sum(rounded_values)
  
  # If the sum is already 100 (or if there's no remainder to distribute), return the floored values.
  if (remainder == 0) {
    return(rounded_values)
  }
  
  # Calculate the fractional parts of the original values used to determine which values should get the extra +1.
  fractional_parts <- values - floor(values)
  
  # Identify the indices of the values ('remainder') that were "cut short" the most when floored and should receive an additional +1 to make the sum 100.
  indices_to_adjust <- order(fractional_parts, decreasing = TRUE)[1:abs(remainder)]
  
  # Distribute the remainder by adding/subtracting 1 to/from the identified values
  if (remainder > 0) { # If sum is < 100, add 1 to the selected values
    rounded_values[indices_to_adjust] <- rounded_values[indices_to_adjust] + 1
  } else { # If sum is > 100 (less common here), subtract 1
    rounded_values[indices_to_adjust] <- rounded_values[indices_to_adjust] - 1
  }
  
  return(rounded_values)
}

  #Relative Biovolume
rel_bv_constrained <- living.x %>% 
    #mutate(BV = replace_na(BV, 0)) %>%
    group_by(sample_num) %>%
    mutate(relative_BV = BV / sum(BV) * 100, rel_BV_constrained_rounded = constrain_round(relative_BV)) %>%
    ungroup()     

  # Verify that sums are exactly 100% for each sample
cat("\n--- Sums for Constrained Rounded Biovolume (should be 100%) ---\n")
 print(rel_bv_constrained %>%
        group_by(sample_num) %>%
        summarise(sum_constrained_BV = sum(rel_BV_constrained_rounded)))
  
print(rel_bv_constrained %>%
    group_by(Sub_type,sample_num) %>% summarise(sum_constrained_BV = sum(rel_BV_constrained_rounded),.groups = "drop") %>% 
    ggplot(aes(x=factor(sample_num), y=sum_constrained_BV, fill=Sub_type)) +
    geom_bar(stat="identity") +
    plankton_groups_colFill +
    scale_y_continuous("Relative biovolume (%)", limits = c(0, 100), expand = c(0,0)) +
    xlab(NULL) +
    ggtitle("Relative biovolume of the living per sample (Constrained Rounded)") +
    theme_bw() +
    theme(axis.text = element_text(size = 10),plot.title = element_text(hjust = 0.5, face = "bold")))
  
  # Relative abundance
 rel_ab_constrained <- living.x %>% 
    #mutate(AB = replace_na(AB, 0)) %>%
    group_by(sample_num) %>%
    mutate(relative_AB = AB / sum(AB) * 100, rel_AB_constrained_rounded = constrain_round(relative_AB)) %>%
    ungroup() 
  
  # Verify that sums are exactly 100% for each sample
cat("\n--- Sums for Constrained Rounded Abundance (should be 100%) ---\n")
 print(rel_ab_constrained %>%
        group_by(sample_num) %>%
        summarise(sum_constrained_AB = sum(rel_AB_constrained_rounded)))

print(rel_ab_constrained %>%    
    group_by(Sub_type,sample_num) %>% summarise(sum_constrained_AB = sum(rel_AB_constrained_rounded),.groups = "drop") %>% 
    ggplot(aes(x=factor(sample_num), y=sum_constrained_AB, fill=Sub_type)) +
    geom_bar(stat="identity") +
    plankton_groups_colFill +
    scale_y_continuous(" Relative abundance (%)", limits = c(0, 100), expand = c(0,0)) +
    xlab(NULL) +
    ggtitle("Relative abundance of the living per sample (Constrained Rounded)") +
    theme_bw() +
    theme(axis.text = element_text(size = 10),plot.title = element_text(hjust = 0.5, face = "bold")))
  
  # Condition in case the dataset do not have non_living objects
  N <- length(unique(x$Sub_type[x$Type=="non_living"]))
  if(N >= 1){
    
  print(x %>% filter(Type=="non_living") %>% group_by(Sub_type,sample_num) %>% summarise(BV = sum(BV),.groups = "drop") %>% 
          ggplot(aes(x=factor(sample_num), y=BV, fill=Sub_type)) +
          geom_bar(stat="identity") +
          plankton_groups_colFill +
          scale_y_continuous("Biovolume (mm3.m-3)", expand = expansion(mult = c(0, 0.05))) +
          xlab(NULL) +
          ggtitle("Biovolume of the non living per sample") +
          theme_bw() +
          theme(axis.text = element_text(size = 10),plot.title = element_text(hjust = 0.5, face = "bold")))

  print(x %>% filter(Type=="non_living") %>% group_by(Sub_type,sample_num) %>% summarise(AB = sum(AB),.groups = "drop") %>%
          ggplot(aes(x=factor(sample_num), y=AB, fill=Sub_type)) +
          geom_bar(stat="identity") +
          plankton_groups_colFill +
          scale_y_continuous("Abundance (ind.m-3)", expand = expansion(mult = c(0, 0.05))) +
          xlab(NULL) +
          ggtitle("Abundance of the non living per sample") +
          theme_bw() +
          theme(axis.text = element_text(size = 10),plot.title = element_text(hjust = 0.5, face = "bold")))
          }
#BV map
  print(ggplot() +
          geom_sf(data = worldmap, color=NA, fill="gray54") +
          geom_sf(data = sample.point, size=2, aes(color= BV)) +
          geom_text_repel(data = sample.point,aes(X, Y, label = sample_num),
                          size = 4,max.overlaps = Inf, box.padding = 0.15, 
                          point.padding = 0.15, min.segment.length = 0.3, seed = 42) +
          scale_color_viridis_c(option = "H") +
          labs(color = "Biovolume (mm3.m-3)", x = NULL, y = NULL) +
          coord_sf(xlim = c(lonmin, lonmax), ylim = c(latmin, latmax), crs = st_crs(worldmap), expand = FALSE) +
          ggtitle("Biovolume of the living per sample") +
          theme_bw() +
          theme(axis.text = element_text(size = 10), plot.title = element_text(hjust = 0.5, face = "bold")))   

#AB map 
print(ggplot() +
          geom_sf(data = worldmap, color=NA, fill="gray54") +
          geom_sf(data = sample.point, size=2, aes(color= AB)) +
          geom_text_repel(data = sample.point,aes(X, Y, label = sample_num),
                          size = 4,max.overlaps = Inf, box.padding = 0.15, 
                          point.padding = 0.15, min.segment.length = 0.3, seed = 42) +
          scale_color_viridis_c(option = "H") +
          labs(color = "Abundance (ind.m-3)", x = NULL, y = NULL)+
          coord_sf(xlim = c(lonmin, lonmax), ylim = c(latmin, latmax), crs = st_crs(worldmap), expand = FALSE) +
          ggtitle("Abundance of the living per sample") +
          theme_bw() +
          theme(axis.text = element_text(size = 10), plot.title = element_text(hjust = 0.5, face = "bold")))

  # 4. NBSS on living
  
  print(living.x %>%
          group_by(sample_num, ESD, class) %>% summarise(BV=sum(BV/norm, na.rm=T), time=unique(time),.groups = "drop") %>%
          ggplot(aes(x=ESD, fill=BV, y=factor(sample_num))) +
          geom_tile() +
          ylab(NULL) +
          scale_x_log10(name = "Size (µm)",breaks = scales::log_breaks(n = 10),labels = scales::label_number()) +
          scale_fill_viridis("NBSS (mm3.mm-3.m-3)", labels=trans_format('log10',math_format(10^.x)), trans="log10", option="turbo") +
          ggtitle("Normalized Biomass Size Spectra of all samples (equivalent to abundance)") +
          theme_bw()+
          theme(axis.text = element_text(size = 10), plot.title = element_text(hjust = 0.5,face = "bold")))

  print(living.x %>% group_by(sample_num, ESD, time) %>% summarise(BV=sum(BV/norm, na.rm=T),.groups = "drop") %>%
          ggplot(aes(x=ESD, y=BV)) +
          geom_point() +
          #facet_wrap(~sample_num, strip.position="top") +
          scale_x_log10(name = "Size (µm)",breaks = scales::log_breaks(n = 10),labels = scales::label_number()) +
          scale_y_log10("NBSS (mm3.mm-3.m-3)", labels=trans_format('log10',math_format(10^.x))) +
          ggtitle("Normalized Biomass Size Spectra of all samples (equivalent to abundance)") +
          theme_bw()+
          theme(axis.text = element_text(size = 10), plot.title = element_text(hjust = 0.5,face = "bold")))


  # Biovolume Composition per size class 
 
  print(living.x %>%
          group_by(class) %>% mutate(rel = BV/sum(BV, na.rm=T)*100) %>%
          group_by(class, ESD, Sub_type) %>% summarise(rel=sum(rel, na.rm=T),.groups = "drop") %>%
          ggplot(aes(x=ESD, y=rel, fill=Sub_type)) +
          geom_col(width=0.03) +
          plankton_groups_colFill +
          scale_y_continuous("Biovolume (%)", expand = c(0, 0)) +
          scale_x_log10(name = "Size (µm)",breaks = scales::log_breaks(n = 10),labels = scales::label_number()) +
          #facet_wrap(~sample_num, strip.position="top") +
          ggtitle("Biovolume composition per size class") +
          theme_classic()+
          theme(axis.text = element_text(size = 10), plot.title = element_text(hjust = 0.5,face = "bold")))

  # Plot of Shannon index 
print (sample.point %>% 
          ggplot(aes(x=factor(sample_num), y=Shannon)) +
          geom_point() +
          labs(y = "Shannon index [0-5]", x = NULL) +
         theme_bw()+
         theme(axis.text = element_text(size = 10), plot.title = element_text(hjust = 0.5,face = "bold")))

 #Shannon map  
  print(ggplot() +
          geom_sf(data = worldmap, color=NA, fill="gray54") +
          geom_sf(data = sample.point, size=2, aes(color= Shannon)) +
          geom_text_repel(data = sample.point,aes(X, Y, label = sample_num),
                          size = 4,max.overlaps = Inf, box.padding = 0.15, 
                          point.padding = 0.15, min.segment.length = 0.3, seed = 42) +
          scale_color_viridis_c() +
          labs(color = "Shannon Index", x = NULL, y = NULL) +
          coord_sf(xlim = c(lonmin, lonmax), ylim = c(latmin, latmax), crs = st_crs(worldmap), expand = FALSE) +
          ggtitle("Map of diversity per sample") +
          theme_bw() +
          theme(axis.text = element_text(size = 10), plot.title = element_text(hjust = 0.5,face = "bold")))   

  # trophic levels on the living
 # Create a colum with the trophic categories
  living.x <- living.x %>% mutate(categorie = case_when(
      Value == 1 ~ "Phototrophs",
      Value == 1.5 ~ "Mixotrophs",
      Value == 2 ~ "Grazers",
      Value == 2.5 ~ "Omnivorous",
      Value == 3 ~ "Predators",
      Value == 3.5 ~ "Unknown",
      Value == -1 ~ "None"))

#Create color map for each trophic category
 color_map_troph <- c( 
  "Unknown" = "#E6E6E6",
  "Predators" = "#C75426", 
  "Omnivorous" = "#FFEBA8", 
  "Grazers" = "#4D8ABA", 
  "Mixotrophs" = "#A0C487",
  "Phototrophs" = "#66B064",
  "None" = "#555555")

 # Calculus of the required variables for geom_rect: xmin, ymin, xmax, and ymax
 plot_data <- living.x %>%
  mutate(trophic_level_num = Value,
    half_width = log(BV + 1), 
    xmin = -half_width,
    xmax = half_width,
    ymin = trophic_level_num - 0.25,
    ymax = trophic_level_num + 0.25,
    trophic_group_name = factor(categorie, levels = names(color_map_troph))) %>%
  arrange(trophic_level_num)

print(ggplot(plot_data) +
  geom_rect(aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax, fill = trophic_group_name)) +
  scale_fill_manual(values = color_map_troph, name = "Trophic groups") +
  scale_y_continuous(breaks = plot_data$trophic_level_num)+
  labs(x = "Log Biovolume +1 (mm³⋅m⁻³)", y = NULL) +
  ggtitle("Trophic pyramid") + 
  theme_classic()+
  theme(axis.text = element_text(size = 10), plot.title = element_text(hjust = 0.5,face = "bold")))                                                             

  sf_use_s2(TRUE)

}




























