#' graph.project
#'
#' Print ggplot graphics to summarise the project (comparison of all samples).
#' Return :
#' 1. Text summary of all the project
#' 2. living/not-living/temporary BV and AB graph
#' 3. Not-Living and Living (based on the OTU database) BV and AB graph
#' 4. NBSS (color and curve)
#' 5. Relative NBSS
#' 6. Shannon index
#'
#' @param x bss data.table produced by "BSS_table"
#' @param metadata metadata table generated by "check_metadata"
#' @param taxo taxonomic table generated with "add_trophiclvl" and "add_taxo"
#' @param bv.type elli, plain or riddled biovolume. default is "elli"
#' @param living.only TRUE by default, for NBSS plots
#'
#' @return A set of graphics to summarise the project.
#' @export
#'
#' @examples graph.project(x=bss table of all the project, metadata, taxo=trophic_affiliation_of_organisms.csv, bv.type="elli", living.only=TRUE)
graph.project <- function(x, metadata, taxo, bv.type="elli", living.only=T) {

  x <- filter(x, type==bv.type) %>% merge(taxo, "object_annotation_hierarchy", all.x=T)
  t <- metadata %>% select(sample_id, sample_num, object_time, object_date) %>%
    mutate(time=as.POSIXct(paste(object_date, object_time))) %>% select(sample_id, sample_num, time)
  x <- merge(x, t, all.x=T)
  x$max <- bv_to_esdum(x$max)

   # Set common color palette
  plankton_groups_colors <- c("#709699", #cyanobacteria
               "#F2F2F2", #detritus
               "#FAFABA", #other
               "#C9C4FF", #ciliophora
               "#B5D493", #dinoflagellata
               "#FAD4EB", #rhizaria
               "#1A9C75", #bacillariophyta
               "#E3E699", #dictyochophyceae
               "#EDB022", #crustacea
               "#E88F6B", #copepoda
               "#B0D6E0", #chaetognatha
               "#3B638A", #tunicata
               "#6999C7", #cnidaria
               "#C68181", #mollusca
               "#668F3B", #coccolithophyceae
               "#FFD3CF", #other_unidentified
               "#0073BD" #plastics
               )

  names(plankton_groups_colors)<- c("cyanobacteria","detritus","other","ciliophora","dinoflagellata",
                     "rhizaria","bacillariophyta","dictyochophyceae","crustacea",
                     "copepoda","chaetognatha","tunicata","cnidaria","mollusca",
                     "coccolithophyceae","other_unidentified","plastics")
  plankton_groups_colScale <- scale_colour_manual(name = "taxonomic group",values = plankton_groups_colors)
  plankton_groups_colFill <- scale_fill_manual(name = "taxonomic group",values = plankton_groups_colors)

  # SUMMARY OF THE PROJECT
  # ----------------------------------------------------------------------------
  div.all <- x %>% group_by(object_annotation_category) %>%
    summarise(AB=sum(AB, na.rm=T)) %>% select(AB) %>% vegan::diversity()
  div <- x[x$n1=="living",] %>% group_by(object_annotation_category) %>%
    summarise(AB=sum(AB, na.rm=T)) %>% select(AB) %>% vegan::diversity()

  text = paste0(
    "\nALL:\n",
    "\nNumber of samples:\n",
    length(unique(x$sample_id)),
    "\nMean abundance (ind.m-3):\n",
    round(mean(x$AB, na.rm=T),2)," ~",round(sd(x$AB, na.rm=T),2),
    "\nMean biovolume (mm3.mm-3):\n",
    round(mean(x$BV, na.rm=T),2)," ~",round(sd(x$BV, na.rm=T),2),
    "\nShannon Index:\n",
    round(div.all,2),

    "\n\n\nLIVING ONLY:\n",
    "\nNumber of samples:\n",
    length(unique(x$sample_id[x$n1=="living"])),
    "\nMean abundance (ind.m-3):\n",
    round(mean(x$AB[x$n1=="living"], na.rm=T),2)," ~",round(sd(x$AB[x$n1=="living"], na.rm=T),2),
    "\nMean biovolume (mm3.mm-3):\n",
    round(mean(x$BV[x$n1=="living"], na.rm=T),2)," ~",round(sd(x$BV[x$n1=="living"], na.rm=T),2),
    "\nShannon Index:\n",
    round(div,2))

  print(ggplot() +
          annotate("text", x = 1, y=10, size=3, label = text) +
          theme_void())

  # BIOVOLUME AND ABUNDANCE TOTAL OF THE PROJECT
  # ----------------------------------------------------------------------------
  # living/not-living/temporary
  print(ggplot(x, aes(x=factor(sample_num), y=BV, fill=n1)) +
          geom_bar(stat="identity") +
          scale_fill_brewer("paired") +
          scale_y_continuous("Biovolume (mm3.m-3)") +
          xlab(NULL) +
          ggtitle("Total biovolume") +
          theme_minimal() +
          theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 1)))

  print(ggplot(x, aes(x=factor(sample_num), y=AB, fill=n1)) +
          geom_bar(stat="identity") +
          scale_fill_brewer("paired") +
          scale_y_continuous("Abundance (ind.m-3)") +
          xlab(NULL) +
          ggtitle("Total abundance") +
          theme_minimal()+
          theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 1)))

  # living only
  N <- length(unique(x$Sub_type[x$n1=="living"]))
  # Total biovolume 
  print(x %>% filter(n1=="living") %>%
          ggplot(aes(x=factor(sample_num), y=BV, fill=Sub_type)) +
          geom_bar(stat="identity") +
          plankton_groups_colFill +
          scale_y_continuous("Biovolume (mm3.m-3)") +
          xlab(NULL) +
          ggtitle("Totale biovolume of the living") +
          theme_minimal() +
          theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 1)))

  # Total abundance 
  print(x %>% filter(n1=="living") %>%
          ggplot(aes(x=factor(sample_num), y=AB, fill=Sub_type)) +
          geom_bar(stat="identity") +
          plankton_groups_colFill +
          scale_y_continuous("Abundance (ind.m-3)") +
          xlab(NULL) +
          ggtitle("Totale abundance of the living") +
          theme_minimal() +
          theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 1)))

# ----------------------------------------------------------------------
# Constrained Rounding Function to have the relative biovolume and relative abundance
# This function takes a vector of percentages (e.g., 33.3, 33.3, 33.4)
# and returns whole numbers that sum exactly to 100 (e.g., 33, 33, 34).
# ----------------------------------------------------------------------
constrain_round <- function(values) {
  # Calculate initial integer parts by rounding down
  rounded_values <- floor(values)
  
  # Calculate how much is 'missing' or 'extra' from 100 after flooring
  remainder <- 100 - sum(rounded_values)
  
  # If the sum is already 100 (or if there's no remainder to distribute), return the floored values.
  if (remainder == 0) {
    return(rounded_values)
  }
  
  # Calculate the fractional parts of the original values used to determine which values should get the extra +1.
  fractional_parts <- values - floor(values)
  
  # Identify the indices of the values ('remainder') that were "cut short" the most when floored and should receive an additional +1 to make the sum 100.
  indices_to_adjust <- order(fractional_parts, decreasing = TRUE)[1:abs(remainder)]
  
  # Distribute the remainder by adding/subtracting 1 to/from the identified values
  if (remainder > 0) { # If sum is < 100, add 1 to the selected values
    rounded_values[indices_to_adjust] <- rounded_values[indices_to_adjust] + 1
  } else { # If sum is > 100 (less common here), subtract 1
    rounded_values[indices_to_adjust] <- rounded_values[indices_to_adjust] - 1
  }
  
  return(rounded_values)
}

  #Relative Biovolume
rel_bv_constrained <- x %>% 
    #mutate(BV = replace_na(BV, 0)) %>%
    filter(n1 == "living" & Sub_type != "detritus") %>%
    group_by(sample_num) %>%
    mutate(relative_BV = BV / sum(BV) * 100, rel_BV_constrained_rounded = constrain_round(relative_BV)) %>%
    ungroup()    

  # Verify that sums are exactly 100% for each sample
cat("\n--- Sums for Constrained Rounded Biovolume (should be 100%) ---\n")
print(rel_bv_constrained %>%
        group_by(sample_num) %>%
        summarise(sum_constrained_BV = sum(rel_BV_constrained_rounded)))
  
print(rel_bv_constrained %>%
    ggplot(aes(x=factor(sample_num), y=rel_BV_constrained_rounded, fill=Sub_type)) +
    geom_bar(stat="identity") +
    plankton_groups_colFill +
    scale_y_continuous("Relative biovolume (%)", limits = c(0, 100)) +
    xlab(NULL) +
    ggtitle("Relative biovolume of the living per sample (Constrained Rounded)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 1)))
  
  # Relative abundance
 rel_ab_constrained <- x %>% 
    #mutate(AB = replace_na(AB, 0)) %>%
    filter(n1 == "living" & Sub_type != "detritus") %>%
    group_by(sample_num) %>%
    mutate(relative_AB = AB / sum(AB) * 100, rel_AB_constrained_rounded = constrain_round(relative_AB)) %>%
    ungroup() 
  
  # Verify that sums are exactly 100% for each sample
cat("\n--- Sums for Constrained Rounded Abundance (should be 100%) ---\n")
print(rel_ab_constrained %>%
        group_by(sample_num) %>%
        summarise(sum_constrained_AB = sum(rel_AB_constrained_rounded)))

       
print(rel_ab_constrained %>%    
    ggplot(aes(x=factor(sample_num), y=rel_AB_constrained_rounded, fill=Sub_type)) +
    geom_bar(stat="identity") +
    plankton_groups_colFill +
    scale_y_continuous(" Relative abundance (%)", limits = c(0, 100)) +
    xlab(NULL) +
    ggtitle("Relative abundance of the living per sample (Constrained Rounded)") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 1)))

  
  # not living only
  N <- length(unique(x$Sub_type[x$n1=="non_living"]))
  print(x %>% filter(n1=="not-living") %>%
          ggplot(aes(x=factor(sample_num), y=BV, fill=Sub_type)) +
          geom_bar(stat="identity") +
          scale_fill_brewer(palette="Set2", na.value="grey") +
          scale_y_continuous("Biovolume (mm3.m-3)") +
          xlab(NULL) +
          ggtitle("Biovolume of the non_living") +
          theme_minimal() +
          theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 1)))

  print(x %>% filter(n1=="not-living") %>%
          ggplot(aes(x=factor(sample_num), y=AB, fill=Sub_type)) +
          geom_bar(stat="identity") +
          scale_fill_brewer(palette="Set2", na.value="grey") +
          scale_y_continuous("Abundance (ind.m-3)") +
          xlab(NULL) +
          ggtitle("Abundance of the non_living") +
          theme_minimal() +
          theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 1)))

  # 4. NBSS on living
  if(living.only==T) x <- x %>% filter(n1=="living" & Sub_type != "detritus")

  print(x %>%
          group_by(sample_num, max, class) %>% summarise(BV=sum(BV/norm, na.rm=T), time=unique(time)) %>%
          ggplot(aes(x=max, fill=BV, y=sample_num)) +
          geom_tile() +
          scale_y_discrete(breaks = x$sample_num, labels = x$sample_num)
          scale_x_log10("Size (um)",labels = scales::trans_format('log10', scales::math_format(10^.x, format = function(x) scales::number(x, accuracy = 0.01)))) +
          scale_fill_viridis("NBSS (mm3.mm-3.m-3)", labels=trans_format('log10',math_format(10^.x)), trans="log10", option="turbo") +
          ggtitle("NBSS on the living") +
          theme_minimal()
          )

  print(x %>% group_by(sample_num, max, time) %>% summarise(BV=sum(BV/norm, na.rm=T)) %>%
          ggplot(aes(x=max, y=BV)) +
          geom_line() +
          facet_wrap(~sample_num, strip.position="top") +
          scale_x_log10("Size (um)", labels = scales::trans_format('log10', scales::math_format(10^.x, format = function(x) scales::number(x, accuracy = 0.01)))) +
          scale_y_log10("NBSS (mm3.mm-3.m-3)", labels=trans_format('log10',math_format(10^.x))) +
          ggtitle("NBSS on the living") +
          theme_minimal()+
          theme(axis.text.x = element_text(size = 7, vjust = 0.5, hjust = 0.5)))


  # Relative BSS
  N <- length(unique(x$Sub_type))
  print(x %>%
          group_by(sample_num, class) %>% mutate(rel = BV/sum(BV, na.rm=T)*100) %>%
          group_by(sample_num, class, max, Sub_type) %>% summarise(rel=sum(rel, na.rm=T)) %>%
          ggplot(aes(x=max, y=rel, fill=Sub_type)) +
          geom_col() +
          plankton_groups_colFill +
          scale_y_continuous("BSS (%)") +
          scale_x_log10("Size (um)", labels = scales::trans_format('log10', scales::math_format(10^.x, format = function(x) scales::number(x, accuracy = 0.01)))) +
          facet_wrap(~sample_num, strip.position="top") +
          ggtitle("Relative BSS") +
          theme_minimal()+
          theme(axis.text.x = element_text(size = 7, vjust = 0.5, hjust = 0.5)))

  # diversity
  print(x %>% group_by(object_annotation_category, sample_num) %>%
          summarise(AB=sum(AB, na.rm=T)) %>% group_by(sample_num) %>%
          summarise(Shannon=vegan::diversity(AB)) %>%
          ggplot(aes(x=sample_num, y=Shannon)) +
          geom_col() +
          coord_flip() +
          xlab(NULL) +
          ggtitle("Diversity") +
          theme_minimal() +
          scale_x_discrete(breaks = unique(x$sample_num)))

  # trophic levels
 # Create a colum with the trophic categories
  x <- x %>% mutate(categorie = case_when(
      Value == 1 ~ "Phototrophs",
      Value == 1.5 ~ "Mixotrophs",
      Value == 2 ~ "Grazers",
      Value == 2.5 ~ "Omnivorous",
      Value == 3 ~ "Predators",
      Value == 3.5 ~ "Unknown",
      Value == -1 ~ "None"))

#Create color map for each trophic category
 color_map_troph <- c(
  "None" = "#555555", 
  "Phototrophs" = "#66B064",  
  "Mixotrophs" = "#A0C487",
  "Grazers" = "#4D8ABA", 
  "Omnivorous" = "#FFEBA8", 
  "Predators" = "#C75426", 
  "Unknown" = "#E6E6E6")

 # Calculus of the required variables for geom_rect: xmin, ymin, xmax, and ymax
 plot_data <- x %>%
  mutate(trophic_level_num = Value,half_width = log(BV + 1), 
    xmin = -half_width,
    xmax = half_width,
    ymin = trophic_level_num - 0.25,
    ymax = trophic_level_num + 0.25,
    trophic_group_name = factor(categorie, levels = names(color_map_troph))) %>%
  arrange(trophic_level_num)

print(ggplot(plot_data) +
  geom_rect(aes(xmin = xmin, ymin = ymin, xmax = xmax, ymax = ymax, fill = trophic_group_name)) +
  scale_fill_manual(values = color_map_troph, name = "Trophic groups") +
  scale_y_continuous(breaks = plot_data$trophic_level_num) +
  labs(x = "Log Biovolume +1 (mm³⋅m⁻³)", y = NULL) +
  ggtitle("Trophic pyramid") + 
  theme_classic())


}
