

#' graph.sample
#'
#' Return ggplot graphics to summarise one sample.
#' 1. Text summary
#' 2. Relative AB and BV
#' 3. Trophic pyramid
#' 4. BSS and NBSS
#' 5. Relative NBSS
#' 6. Map
#'
#' @param x BSS table for one sample
#' @param metadata metadata table generated by "check_metadata"
#' @param bv.type elli, plain or riddled biovolume
#' @param living.only TRUE by default
#' @param taxo taxonomic table generated with "add_trophiclvl" and "add_taxo"
#'
#' @return A set of graphics to summarise the sample.
#' @export
#'
#' @examples graph.sample(x=bss of one sample, metadata, trophic_affiliation_of_organisms.csv, bv.type="elli", living.only=TRUE)

graph.sample <- function(x, metadata, taxo, bv.type="elli", living.only=T) {
 
  # Select type of biovolume
  x <- filter(x, type==bv.type)

  # Unite taxonomiques
  x <- merge(x, taxo, "object_annotation_hierarchy", all.x=T)

  # Filter living
  if (living.only==T) {
    x <- filter(x, n1=="living")
    taxo <- filter(taxo, n1=="living")
  }

 # Set color palette
  plankton_groups_colors <- c("#709699", #cyanobacteria
               "#F2F2F2", #detritus
               "#FAFABA", #other
               "#C9C4FF", #ciliophora
               "#B5D493", #dinoflagellata
               "#FAD4EB", #rhizaria
               "#1A9C75", #bacillariophyta
               "#E3E699", #dictyochophyceae
               "#EDB022", #crustacea
               "#E88F6B", #copepoda
               "#B0D6E0", #chaetognatha
               "#3B638A", #tunicata
               "#6999C7", #cnidaria
               "#C68181", #mollusca
               "#668F3B", #coccolithophyceae
               "#FFD3CF", #other_unidentified
               "#0073BD" #plastics
               )
  
  names(plankton_groups_colors)<- c("cyanobacteria","detritus","other","ciliophora","dinoflagellata",
                     "rhizaria","bacillariophyta","dictyochophyceae","crustacea",
                     "copepoda","chaetognatha","tunicata","cnidaria","mollusca",
                     "coccolithophyceae","other_unidentified","plastics")
  plankton_groups_colScale <- scale_colour_manual(name = "Taxonomic group",values = plankton_groups_colors)
  plankton_groups_colFill <- scale_fill_manual(name = "Taxonomic group",values = plankton_groups_colors)

  # ------------------------------------------------------------------------------
  # Resume
  div <- x %>% group_by(object_annotation_category) %>%
    summarise(AB=sum(AB, na.rm=T)) %>% select(AB) %>% vegan::diversity()
  text = paste0(
    "\n\nTotal absolute abundance (ind.m-3):\n",
    round(sum(x$AB, na.rm=T),4),
    "\nTotal absolute biovolume (mm3.mm-3):\n",
    round(sum(x$BV, na.rm=T),4),
    "\nShannon Index:\n",
    round(div,4))
  p1 <- ggplot() +
    annotate("text", x = 1, y=10, size=4, label = text) +
    theme_void()

  # Relative abundance
  tot <- sum(sum(x$AB, na.rm=T))

  p2 <- x %>% group_by(Sub_type) %>%
    summarise(per=sum(AB, na.rm=T)/tot*100) %>%
    ggplot(aes(x="", y=per, fill=Sub_type)) +
    geom_bar(stat="identity", width=1, size=0.15, color="black") +
    plankton_groups_colFill +
    coord_polar("y", start=0) +
    ggtitle("Relative abundance") +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5, vjust = -4,size = 10,face = "bold"))

  # Relative biovolume
  tot <- sum(sum(x$BV, na.rm=T))

  p3 <- x %>% group_by(Sub_type) %>%
    summarise(per=sum(BV, na.rm=T)/tot*100) %>%
    ggplot(aes(x="", y=per, fill=Sub_type)) +
    geom_bar(stat="identity", width=0.25, size=0.15, color="black") +
    plankton_groups_colFill +
    coord_polar("y", start=0) +
    ggtitle("Relative biovolume") +
    theme_void() +
    theme(plot.title = element_text(hjust = 0.5, vjust = -4,size = 10,face = "bold"))

  # NBSS
  p4 <- x %>% group_by(max) %>% summarise(BV=sum(BV/norm, na.rm=T)) %>%
    ggplot(aes(x=bv_to_esdum(max), y=BV)) +
     geom_point(size=2, fill="lightgrey", colour="black",shape=21) +
    scale_x_log10("Size on ESD (\u00b5m)") +
    scale_y_log10("NBSS (mm\u00b3.mm\u207B\u00b3.m\u207B\u00b3)", labels=trans_format('log10',math_format(10^.x))) +
    theme_bw() +
    ggtitle("NBSS") +
    theme(plot.title = element_text(hjust = 0.5, size = 10,face = "bold"), legend.text = element_text(size = 0.5))

  # BSS
  p5 <- x %>% group_by(max) %>% summarise(BV=sum(BV, na.rm=T)) %>%
    ggplot(aes(x=bv_to_esdum(max), y=BV)) +
    geom_point(size=2, fill="lightgrey", colour="black",shape=21) +
    scale_x_log10("Size on ESD (\u00b5m)") +
    scale_y_log10("BSS (mm\u00b3.m\u207B\u00b3)", labels=trans_format('log10',math_format(10^.x))) +
    theme_bw() +
    ggtitle("BSS") +
    theme(plot.title = element_text(hjust = 0.5, size = 10,face = "bold"), legend.text = element_text(size = 0.5))

  # BV compo/size class
  p6 <- x %>% group_by(Sub_type, max, class) %>%
    group_by(class) %>% mutate(per = BV/sum(BV, na.rm=T)*100) %>%
    group_by(class, max, Sub_type) %>% summarise(per=sum(per, na.rm=T)) %>%
    ggplot(aes(x=bv_to_esdum(max), y=per, fill=Sub_type)) +
    geom_col(position = "fill", width = 0.02) +
    plankton_groups_colFill +
    ylab("Biovolume (%)") +
    scale_x_log10("Size on ESD (\u00b5m)") +
    ggtitle("Biovolume composition per size class") +
    theme_classic() +
    theme(plot.title = element_text(hjust = 0.5, size = 10,face = "bold"), legend.text = element_text(size = 0.5))

  # Trophic pyramid p7
  x$categorie[x$Value==1] <- "Phototrophs"
  x$categorie[x$Value==1.5] <- "Mixotrophs"
  x$categorie[x$Value==2] <- "Grazers"
  x$categorie[x$Value==2.5] <- "Omnivorous"
  x$categorie[x$Value==3] <- "Predators"
  x$categorie[x$Value==3.5] <- "Unknown"
  x$categorie[x$Value==-1] <- "None"

 color_map_troph <- c(
  "None" = "#FFFFFF", 
  "Phototrophs" = "#66B064",  
  "Mixotrophs" = "#A0C487",
  "Grazers" = "#4D8ABA", 
  "Omnivorous" = "#FFEBA8", 
  "Predators" = "#C75426", 
  "Unknown" = "#E6E6E6")

  #p7 <- ggplot(x, aes(x=reorder(categorie,Value), y=BV)) +
   # geom_col() +
   # scale_fill_brewer(palette="Set2") +
   # coord_flip() +
   # xlab(NULL) +
    #ylab("log biovolume +1 (mm\u00b3.m\u207B\u00b3)") +
    #ggtitle("Trophic level biovolume") +
   # theme_classic()

p7<- ggplot(x, aes(x=reorder(categorie,Value), y=BV)) +
   geom_tile(aes(x = 0, y = Value, width = ((log(BV) + 1) * 2), height = 0.5, fill = categorie), color = "black", linewidth = 0.5) +
    scale_fill_manual(values = color_map_troph, name = "Trophic groups") +
    labs(x = "Log Biovolume +1 (mm³/m³)\n(Equivalent abundance)", y = NULL) +
  ggtitle("Trophic Pyramids") +
  theme_minimal() + 
  theme(
    plot.title = element_text(hjust = 0.5, size = 12), # Center and size title
    axis.title.x = element_text(size = 8),
    axis.text.y = element_blank(), # Remove y-axis numbers/labels as they are implied by the levels
    axis.ticks.y = element_blank(), # Remove y-axis ticks
    panel.grid.major.y = element_blank(), # Remove horizontal grid lines
    panel.grid.minor.y = element_blank(),
    legend.title = element_text(size = 10, hjust = 0.5), # Legend title font size and center
    legend.text = element_text(size = 8), # Legend item font size
    legend.position = c(0.15, 0.25), # Example: Adjust these values to fine-tune position
    legend.justification = c("left", "bottom"), # Justify the legend box from its bottom-left corner
    legend.direction = "horizontal", # Arrange items horizontally
    legend.box = "horizontal", # Arrange legend keys and labels horizontally
    legend.box.just = "left",
    legend.key.size = unit(0.5, "cm"), # Adjust legend key size if needed
    legend.spacing.x = unit(0.2, "cm"), # Spacing between legend items
    legend.spacing.y = unit(0.2, "cm"),
    legend.background = element_rect(fill = "white", color = "grey", linewidth = 0.5)) +
    guides(fill = guide_legend(ncol = 2, title = "Trophic groups"))

  # Map
    ##Extract Lat/Lon, load world map and convert xy points as sf objects
  meta.x <- filter(metadata, sample_id==unique(x$sample_id))
  worldmap <- ne_countries(scale = 'medium', type = 'map_units', returnclass = 'sf')
  meta.point <- st_as_sf(meta.x, coords=c("object_lon","object_lat"), crs=4326)

  ##Problem with Pacific ocean projections
  if(any(meta.x$object_lon >= 130) | any(meta.x$object_lon <= -110)) {

    # Transform longitudes : [-180,180] → [0,360]
    meta.x <- meta.x %>%
      mutate(object_lon_wrapped = ifelse(object_lon < 0, object_lon + 360, object_lon))
    meta.point <- st_as_sf(meta.x, coords=c("object_lon_wrapped","object_lat"), crs=4326)

    #Set Robinson projection centered on Pacific
    robinson <- "+proj=robin +lon_0=180 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
    world_robinson<- worldmap %>%
      st_break_antimeridian(lon_0 = 180) %>%
      st_transform(crs = robinson)

    p8 <- ggplot() +
      geom_sf(data = world_robinson, color=NA, fill="gray54",) +
      geom_sf(data = meta.point, size=1, color="red") +
      theme_bw()

  }else{

    #Set Robinson projection centered on Atlantic
    robinson <- "+proj=robin +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
    world_robinson<- worldmap %>%
      #st_break_antimeridian(lon_0 = 180) %>%
      st_transform(crs = robinson)

  p8 <- ggplot() +
    geom_sf(data = world_robinson, color=NA, fill="gray54") +
    geom_sf(data = meta.point, size=0.8, color="red") +
    theme_bw()
}
  ptot <- ggarrange(p1, p2, p3, p7, p5, p4, p6, p8,
                 common.legend = T, legend="bottom",
                 ncol=4, nrow=2) %>%
    annotate_figure(top=unique(x$sample_id), fig.lab.face="bold")

  # sf_use_s2(TRUE)

  return(ptot)
}
